### ISSUE TITLE
Add scan averaging

### ISSUE THREAD

**Issue by slactjohnson** [pcdshub/las-dispersion-scan#26]
## Desired Behavior
It would be desirable to be able to perform multiple complete scans and average them, taking a configurable number of spectra at each point. 

## Current Behavior
Currently we only provide the facility for taking a number of spectra and averaging at each position. 

## Possible Solution
Add a new configuration parameter, adjust the scanning routine to support this. 

## Context
Averaging spectra at each point does not provide the same SNR as averaging over multiple scans.

**Comment by klauer** [comment]
The issue calls it out well, but just to be extra clear about my goal -

I plan to implement this as an addition to the scanning code rather than replacing the current functionality, as in
* Retain support for acquiring multiple spectra at a single position prior to moving.
* Add support for multiple scans to be averaged

Additionally, motor readback positions from the same point in each scan will also need to be averaged, as they may fluctuate a bit - though hopefully within the position deadband
